from __future__ import annotations

import argparse
import sys
from pathlib import Path

_CONTROLLER_TEMPLATE = '''"""Starter controller generated by `validator-gateway init`.

Replace this with your own controller(s): subclass BaseController, inject
whatever services/repositories you need, and raise validator_gateway
DomainError subclasses (NotFoundError, ConflictError, ...) for business-rule
failures. This file is a working example, not something you're meant to
keep — delete it once you have real controllers.
"""

from validator_gateway import BaseController, NotFoundError


class ExampleController(BaseController):
    async def get_example(self, example_id: str):
        if example_id != "1":
            raise NotFoundError(f"Example {example_id} not found")
        return {"id": example_id, "name": "Example"}
'''

_GATEWAY_TEMPLATE = '''"""Starter gateway generated by `validator-gateway init`.

A synchronous REST route generally wants this gateway as-is: fail-fast, no
`recovery=` attached (see Design Decision 8 in the build plan). A worker or
agent that wants retry/redirect/queue behavior instead attaches a
RecoveryEngine here — see docs/recovery_policies.md.
"""

from validator_gateway import ValidatorGateway, default_logging_hook

from controllers.example_controller import ExampleController

gateway = ValidatorGateway(
    controller=ExampleController(),
    on_exception=default_logging_hook(),
)
'''

_FILES: dict[str, str] = {
    "controllers/__init__.py": "",
    "controllers/example_controller.py": _CONTROLLER_TEMPLATE,
    "validator_gateways/__init__.py": "",
    "validator_gateways/example_gateway.py": _GATEWAY_TEMPLATE,
}

_SOURCE_JSON_TEMPLATE = '''from dataclasses import dataclass


@dataclass(frozen=True)
class SourceJson:
    """What every *ValidatorGateway requires its caller to declare about
    itself — not inferred, not defaulted. An HTTP route passes its own
    real request path and REST method; a worker or agent caller has no
    REST method at all, so `method` is optional — only `url` (or whatever
    identifies the call site: a queue name, a job name) and `caller_type`
    are universal.

    This is what a traffic log can tag every line with, so a log reader
    can tell which route (or worker, or agent) actually drove a given
    call — not just which gateway class happened to handle it.
    """

    url: str
    caller_type: str
    method: str | None = None

    def as_dict(self) -> dict[str, str | None]:
        return {"url": self.url, "method": self.method, "caller_type": self.caller_type}
'''

_CLASSIFYING_BASE_TEMPLATE = '''"""Shared plumbing for a "classifying" ValidatorGateway: one that
classifies failures into an explicit enum and resolves each case via a
visible match/case block, instead of relying only on the package's
generic try/except.

This is deliberately NOT part of the validator_gateway package — the
whole point of the pattern is that you can open a subclass of this file
(generated alongside it by `validator-gateway add-feature`) and see
exactly how failures are classified and resolved, without digging into
package internals. This file only factors out the mechanics that are
identical across every such gateway (the try/except wrapper, the
severity fallback, and an always-log guarantee); it does NOT decide what
any specific failure means — that's each subclass's job, via
`_KNOWN_CASES`, `_severity_fallback()`, and `_resolve()`.

Generated once by `validator-gateway add-feature` and then owned by your
project — edit or replace this however you like; nothing in the package
depends on it.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable, Coroutine
from enum import Enum
from typing import Any, TypeVar

from pydantic import BaseModel
from validator_gateway import (
    DomainError,
    ErrorResponse,
    ExceptionHook,
    SuccessResponse,
    ValidatorGateway,
    resolve_status,
)
from validator_gateway.responses import build_error_response

from .source_json import SourceJson

ControllerT = TypeVar("ControllerT")

_traffic_log = logging.getLogger("validator_gateway.traffic")


def _to_jsonable(value: Any) -> Any:
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    return value


class ClassifyingValidatorGateway(ValidatorGateway[ControllerT]):
    """Subclasses must define, at minimum:

      - `_KNOWN_CASES: dict[str, Enum]` (class attribute) — maps a
        DomainError.code to one of your own enum members. The
        developer-extensible recategorization layer: add an entry to give
        a code bespoke handling in _resolve().
      - `_severity_fallback(self, is_server_error: bool) -> Enum` — which
        enum member to use for a code with no entry in `_KNOWN_CASES`,
        decided purely from the HTTP status its default mapping implies.
      - `async def _resolve(self, case, exc, action, args) -> response` —
        the match/case block deciding what each case actually means.

    handle() itself always catches, classifies, resolves, and logs — a
    subclass cannot forget any of these by construction.
    """

    _KNOWN_CASES: dict[str, Enum] = {}

    def __init__(
        self,
        controller: ControllerT,
        *,
        source_json: SourceJson,
        on_exception: ExceptionHook | None = None,
    ) -> None:
        super().__init__(controller, on_exception=on_exception)
        self.source_json = source_json

    def _severity_fallback(self, is_server_error: bool) -> Enum:
        raise NotImplementedError(
            f"{type(self).__name__} must implement _severity_fallback() -> Enum, "
            "returning its own CLIENT_ERROR/SERVER_ERROR-equivalent case."
        )

    async def _resolve(
        self,
        case: Enum,
        exc: DomainError,
        action: Callable[..., Coroutine[Any, Any, Any]],
        args: tuple[Any, ...],
    ) -> SuccessResponse[Any] | ErrorResponse:
        raise NotImplementedError(f"{type(self).__name__} must implement _resolve().")

    def _classify(self, exc: DomainError) -> Enum:
        specific = self._KNOWN_CASES.get(exc.code)
        if specific is not None:
            return specific
        mapping = resolve_status(exc)
        return self._severity_fallback(mapping.http_status >= 500)

    async def handle(
        self,
        action: Callable[..., Coroutine[Any, Any, Any]],
        *args: Any,
        **kwargs: Any,
    ) -> SuccessResponse[Any] | ErrorResponse:
        case_value = "success"
        try:
            result = await action(*args, **kwargs)
            response: SuccessResponse[Any] | ErrorResponse = SuccessResponse(data=result)
        except DomainError as exc:
            case = self._classify(exc)
            case_value = case.value
            response = await self._resolve(case, exc, action, args)
        except Exception as exc:  # noqa: BLE001 - matches the core's own catch-all boundary
            case_value = "unclassified"
            hidden = self.config.hide_internal_errors
            wrapped = DomainError(
                message="An unexpected error occurred." if hidden else str(exc), cause=exc
            )
            response = build_error_response(wrapped)

        request_payload: list[Any] = [_to_jsonable(a) for a in args]
        if kwargs:
            request_payload.append({k: _to_jsonable(v) for k, v in kwargs.items()})
        _traffic_log.info(
            "source=%s method=%s case=%s request=%s response=%s",
            json.dumps(self.source_json.as_dict()),
            action.__name__,
            case_value,
            json.dumps(request_payload),
            json.dumps(response.model_dump(mode="json")),
        )
        return response
'''

_FEATURE_CONTROLLER_TEMPLATE = '''"""Controller for the "{name}" feature, generated by
`validator-gateway add-feature {name}`.

Replace this with real business logic — inject whatever services or
repositories you need, and raise validator_gateway DomainError subclasses
(NotFoundError, ConflictError, ValidationFailedError, ...) for
business-rule failures. See validator_gateways/{name}_validator_gateway.py
for where those get classified into a FailureCase and turned into a
response.
"""

from validator_gateway import BaseController, NotFoundError


class {class_name}Controller(BaseController):
    async def get_{name}(self, {name}_id: str):
        if {name}_id != "1":
            raise NotFoundError("{class_name} " + {name}_id + " not found")
        return {{"id": {name}_id, "name": "Example {class_name}"}}
'''

_FEATURE_GATEWAY_TEMPLATE = '''"""The gateway for the "{name}" feature, generated by
`validator-gateway add-feature {name}`.

Built on ClassifyingValidatorGateway
(validator_gateways/classifying_validator_gateway.py) — see
examples/fastapi_kanban/validator_gateways/board_validator_gateway.py in
the validator_gateway repo for a fuller worked example, including a
redirect to a different gateway.

Edit FailureCase, _KNOWN_CASES, and _resolve() below to match your own
feature's actual failure modes — this is a starting skeleton, not a
finished implementation.
"""

from __future__ import annotations

from enum import Enum

from validator_gateway import DomainError, ErrorResponse, default_logging_hook
from validator_gateway.responses import build_error_response

from controllers.{name}_controller import {class_name}Controller
from validator_gateways.classifying_validator_gateway import ClassifyingValidatorGateway
from validator_gateways.source_json import SourceJson


class FailureCase(Enum):
    """Every failure case this gateway explicitly recognizes — add one per
    business-rule failure your controller actually raises. Anything not
    listed here still gets a response (via the severity fallback below),
    it just won't get bespoke handling until you add a case for it."""

    NOT_FOUND = "not_found"
    CLIENT_ERROR = "client_error"  # severity fallback: any other 4xx-mapped code
    SERVER_ERROR = "server_error"  # severity fallback: any other 5xx-mapped code


class {class_name}ValidatorGateway(ClassifyingValidatorGateway[{class_name}Controller]):
    """`source_json` is required, not inferred — the caller must declare
    its own url, caller_type, and (for an HTTP caller) REST method."""

    _KNOWN_CASES: dict[str, Enum] = {{
        "not_found": FailureCase.NOT_FOUND,
    }}

    def __init__(self, *, source_json: SourceJson) -> None:
        super().__init__(
            {class_name}Controller(), source_json=source_json, on_exception=default_logging_hook()
        )

    def _severity_fallback(self, is_server_error: bool) -> FailureCase:
        return FailureCase.SERVER_ERROR if is_server_error else FailureCase.CLIENT_ERROR

    async def _resolve(self, case: Enum, exc: DomainError, action, args) -> ErrorResponse:
        match case:
            case _:
                return build_error_response(exc)
'''


def _init(path: Path, force: bool) -> int:
    existing = [name for name in _FILES if (path / name).exists()]
    if existing and not force:
        print(
            "The following files already exist (pass --force to overwrite):",
            file=sys.stderr,
        )
        for name in existing:
            print(f"  {path / name}", file=sys.stderr)
        return 1

    created = []
    for name, content in _FILES.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(name)

    print(f"Created in {path}:")
    for name in created:
        print(f"  {name}")
    return 0


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _add_feature(path: Path, name: str, force: bool) -> int:
    if not name.isidentifier() or name != name.lower():
        print(
            f"Feature name must be a lowercase, snake_case identifier: {name!r}",
            file=sys.stderr,
        )
        return 1

    class_name = _pascal_case(name)
    feature_files: dict[str, str] = {
        f"controllers/{name}_controller.py": _FEATURE_CONTROLLER_TEMPLATE.format(
            name=name, class_name=class_name
        ),
        f"validator_gateways/{name}_validator_gateway.py": _FEATURE_GATEWAY_TEMPLATE.format(
            name=name, class_name=class_name
        ),
    }
    # Generated once, shared across every feature — never overwritten by
    # --force, since they aren't feature-specific and a developer may have
    # already customized them.
    shared_files: dict[str, str] = {
        "controllers/__init__.py": "",
        "validator_gateways/__init__.py": "",
        "validator_gateways/classifying_validator_gateway.py": _CLASSIFYING_BASE_TEMPLATE,
        "validator_gateways/source_json.py": _SOURCE_JSON_TEMPLATE,
    }

    existing = [rel_name for rel_name in feature_files if (path / rel_name).exists()]
    if existing and not force:
        print(
            "The following files already exist (pass --force to overwrite):",
            file=sys.stderr,
        )
        for rel_name in existing:
            print(f"  {path / rel_name}", file=sys.stderr)
        return 1

    created = []
    for rel_name, content in feature_files.items():
        target = path / rel_name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(rel_name)

    for rel_name, content in shared_files.items():
        target = path / rel_name
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(rel_name)

    print(f"Created in {path}:")
    for rel_name in created:
        print(f"  {rel_name}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="validator-gateway")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init", help="Scaffold controllers/ and validator_gateways/ starter files."
    )
    init_parser.add_argument(
        "--path",
        type=Path,
        default=Path.cwd(),
        help="Target directory (default: current directory).",
    )
    init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing files."
    )

    add_feature_parser = subparsers.add_parser(
        "add-feature",
        help=(
            "Scaffold a {name}_controller.py + {name}_validator_gateway.py pair "
            "(a 'classifying' gateway with a visible FailureCase enum and "
            "match/case block), so you don't hand-write that boilerplate "
            "for every new feature."
        ),
    )
    add_feature_parser.add_argument("name", help="Feature name, snake_case (e.g. 'invoice').")
    add_feature_parser.add_argument(
        "--path",
        type=Path,
        default=Path.cwd(),
        help="Target directory (default: current directory).",
    )
    add_feature_parser.add_argument(
        "--force", action="store_true", help="Overwrite this feature's own files if they exist."
    )

    args = parser.parse_args(argv)

    if args.command == "init":
        return _init(args.path, args.force)
    if args.command == "add-feature":
        return _add_feature(args.path, args.name, args.force)

    parser.print_help()
    return 1
