from __future__ import annotations

import argparse
import sys
from pathlib import Path

_CONTROLLER_TEMPLATE = '''"""Starter controller generated by `validator-gateway init`.

Replace this with your own controller(s): subclass BaseController, inject
whatever services/repositories you need, and raise validator_gateway
DomainError subclasses (NotFoundError, ConflictError, ...) for business-rule
failures. This file is a working example, not something you're meant to
keep — delete it once you have real controllers.
"""

from validator_gateway import BaseController, NotFoundError


class ExampleController(BaseController):
    async def get_example(self, example_id: str):
        if example_id != "1":
            raise NotFoundError(f"Example {example_id} not found")
        return {"id": example_id, "name": "Example"}
'''

_GATEWAY_TEMPLATE = '''"""Starter gateway generated by `validator-gateway init`.

A synchronous REST route generally wants this gateway as-is: fail-fast, no
`recovery=` attached (see Design Decision 8 in the build plan). A worker or
agent that wants retry/redirect/queue behavior instead attaches a
RecoveryEngine here — see docs/recovery_policies.md.
"""

from validator_gateway import ValidatorGateway, default_logging_hook

from controllers.example_controller import ExampleController

gateway = ValidatorGateway(
    controller=ExampleController(),
    on_exception=default_logging_hook(),
)
'''

_FILES: dict[str, str] = {
    "controllers/__init__.py": "",
    "controllers/example_controller.py": _CONTROLLER_TEMPLATE,
    "validator_gateways/__init__.py": "",
    "validator_gateways/example_gateway.py": _GATEWAY_TEMPLATE,
}


def _init(path: Path, force: bool) -> int:
    existing = [name for name in _FILES if (path / name).exists()]
    if existing and not force:
        print(
            "The following files already exist (pass --force to overwrite):",
            file=sys.stderr,
        )
        for name in existing:
            print(f"  {path / name}", file=sys.stderr)
        return 1

    created = []
    for name, content in _FILES.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(name)

    print(f"Created in {path}:")
    for name in created:
        print(f"  {name}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="validator-gateway")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init", help="Scaffold controllers/ and validator_gateways/ starter files."
    )
    init_parser.add_argument(
        "--path",
        type=Path,
        default=Path.cwd(),
        help="Target directory (default: current directory).",
    )
    init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing files."
    )

    args = parser.parse_args(argv)

    if args.command == "init":
        return _init(args.path, args.force)

    parser.print_help()
    return 1
