"""Starter controller generated by `validator-gateway init`.

Replace this with your own controller(s): subclass BaseController, inject
whatever services/repositories you need, and raise validator_gateway
DomainError subclasses (NotFoundError, ConflictError, ...) for business-rule
failures. This file is a working example, not something you're meant to
keep — delete it once you have real controllers.
"""

from validator_gateway import BaseController, NotFoundError


class ExampleController(BaseController):
    async def get_example(self, example_id: str):
        if example_id != "1":
            raise NotFoundError(f"Example {example_id} not found")
        return {"id": example_id, "name": "Example"}
