"""Starter controller generated by `atlasboxpy-controller init`.

Replace this with your own controller(s): subclass BaseController, inject
whatever services/repositories you need, and build a SuccessResponse or
ErrorResponse directly for any outcome your service already knows about
(see docs/extending.md). Raising an atlasboxpy_controller DomainError subclass
(NotFoundError, ConflictError, ...) still works as a convenience escape
hatch for anything simpler than that. This file is a working example, not
something you're meant to keep — delete it once you have real controllers.
"""

from atlasboxpy_controller import BaseController, NotFoundError


class ExampleController(BaseController):
    async def get_example(self, example_id: str):
        if example_id != "1":
            raise NotFoundError(f"Example {example_id} not found")
        return {"id": example_id, "name": "Example"}
