from __future__ import annotations

import argparse
import sys
from pathlib import Path

_CONTROLLER_TEMPLATE = '''"""Starter controller generated by `atlasboxpy-controller init`.

Replace this with your own controller(s): subclass BaseController, inject
whatever services/repositories you need, and build a SuccessResponse or
ErrorResponse directly for any outcome your service already knows about
(see docs/extending.md). Raising an atlasboxpy_controller DomainError subclass
(NotFoundError, ConflictError, ...) still works as a convenience escape
hatch for anything simpler than that. This file is a working example, not
something you're meant to keep — delete it once you have real controllers.
"""

from atlasboxpy_controller import BaseController, NotFoundError


class ExampleController(BaseController):
    async def get_example(self, example_id: str):
        if example_id != "1":
            raise NotFoundError(f"Example {example_id} not found")
        return {"id": example_id, "name": "Example"}
'''

_FILES: dict[str, str] = {
    "controllers/__init__.py": "",
    "controllers/example_controller.py": _CONTROLLER_TEMPLATE,
}

_FEATURE_CONTROLLER_TEMPLATE = '''"""Controller for the "{name}" feature, generated by
`atlasboxpy-controller add-feature {name}`.

Replace this with real business logic — inject whatever services or
repositories you need. Build a SuccessResponse/ErrorResponse directly for
any outcome your service already knows about; raising an atlasboxpy_controller
DomainError subclass (NotFoundError, ConflictError, ValidationFailedError,
...) still works as a convenience escape hatch for anything simpler than
that. This is a starting skeleton, not a finished implementation.
"""

from atlasboxpy_controller import BaseController, NotFoundError


class {class_name}Controller(BaseController):
    async def get_{name}(self, {name}_id: str):
        if {name}_id != "1":
            raise NotFoundError("{class_name} " + {name}_id + " not found")
        return {{"id": {name}_id, "name": "Example {class_name}"}}
'''


def _init(path: Path, force: bool) -> int:
    existing = [name for name in _FILES if (path / name).exists()]
    if existing and not force:
        print(
            "The following files already exist (pass --force to overwrite):",
            file=sys.stderr,
        )
        for name in existing:
            print(f"  {path / name}", file=sys.stderr)
        return 1

    created = []
    for name, content in _FILES.items():
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(name)

    print(f"Created in {path}:")
    for name in created:
        print(f"  {name}")
    return 0


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _add_feature(path: Path, name: str, force: bool) -> int:
    if not name.isidentifier() or name != name.lower():
        print(
            f"Feature name must be a lowercase, snake_case identifier: {name!r}",
            file=sys.stderr,
        )
        return 1

    class_name = _pascal_case(name)
    feature_files: dict[str, str] = {
        f"controllers/{name}_controller.py": _FEATURE_CONTROLLER_TEMPLATE.format(
            name=name, class_name=class_name
        ),
    }
    # __init__.py, generated once and never overwritten by --force.
    shared_files: dict[str, str] = {"controllers/__init__.py": ""}

    existing = [rel_name for rel_name in feature_files if (path / rel_name).exists()]
    if existing and not force:
        print(
            "The following files already exist (pass --force to overwrite):",
            file=sys.stderr,
        )
        for rel_name in existing:
            print(f"  {path / rel_name}", file=sys.stderr)
        return 1

    created = []
    for rel_name, content in feature_files.items():
        target = path / rel_name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(rel_name)

    for rel_name, content in shared_files.items():
        target = path / rel_name
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        created.append(rel_name)

    print(f"Created in {path}:")
    for rel_name in created:
        print(f"  {rel_name}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="atlasboxpy-controller")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init", help="Scaffold a controllers/ starter file."
    )
    init_parser.add_argument(
        "--path",
        type=Path,
        default=Path.cwd(),
        help="Target directory (default: current directory).",
    )
    init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing files."
    )

    add_feature_parser = subparsers.add_parser(
        "add-feature",
        help=(
            "Scaffold a {name}_controller.py starter for a new feature, so "
            "you don't hand-write that boilerplate every time."
        ),
    )
    add_feature_parser.add_argument("name", help="Feature name, snake_case (e.g. 'invoice').")
    add_feature_parser.add_argument(
        "--path",
        type=Path,
        default=Path.cwd(),
        help="Target directory (default: current directory).",
    )
    add_feature_parser.add_argument(
        "--force", action="store_true", help="Overwrite this feature's own files if they exist."
    )

    args = parser.parse_args(argv)

    if args.command == "init":
        return _init(args.path, args.force)
    if args.command == "add-feature":
        return _add_feature(args.path, args.name, args.force)

    parser.print_help()
    return 1
