"""Starter gateway generated by `validator-gateway init`.

A synchronous REST route generally wants this gateway as-is: fail-fast, no
`recovery=` attached (see Design Decision 8 in the build plan). A worker or
agent that wants retry/redirect/queue behavior instead attaches a
RecoveryEngine here — see docs/recovery_policies.md.
"""

from validator_gateway import ValidatorGateway, default_logging_hook

from controllers.example_controller import ExampleController

gateway = ValidatorGateway(
    controller=ExampleController(),
    on_exception=default_logging_hook(),
)
